server:
    port: 8081
spring:
    redis:
        host: localhost
        port: 6379
        database: 0
    rabbitmq:
        host: localhost
        port: 5672
        username: admin
        password: 123456
        virtual-host: /
        connection-timeout: 5000
    datasource:
        url: jdbc:mysql://ecs01:3306/spike?serverTimeZone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: huangxiaodong
mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true