spring:
  datasource:
    username: root
    password: huangxiaodong
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rrow.xyz:3307/redisstudy?serverTimezone=GMT%2B8
  redis:
    host: 47.110.255.68
    port: 8000
    database: 0
    connect-timeout: 10000
    timeout: 10000
    lettuce:
      pool:
        max-idle: 8
        min-idle: 3
        max-active: 8
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
