server:
    port: 8761      # \u6E90\u7801\u5B9A\u6B7B\u4E86
spring:
    application:
        name: eruka-server
eureka:
    server:
        eviction-interval-timer-in-ms: 10000
        renewal-percent-threshold: 0.85

    instance:
        hostname: server
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 5
        instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

