server:
    port: 8761
spring:
    application:
        name: eruka-server
eureka:
    server:
        eviction-interval-timer-in-ms: 10000
        renewal-percent-threshold: 0.85
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}      # 手动指定注册地址
        fetch-registry: true
        register-with-eureka: true
    instance:
        hostname: ${APP_HOST:localhost}
        prefer-ip-address: ${IP_ADDRESS:true}
        lease-renewal-interval-in-seconds: 5
        instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

