server:
    port: 8080
fdfs:
    so-timeout: 2500                # \u8BFB\u53D6\u65F6\u95F4
    connect-timeout: 600            # \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
    thumb-image:                    # \u7F29\u7565\u56FE
        width: 100
        height: 100
    tracker-list:
        - rrow.xyz:22122
myfile:
    allow-type:
        - image/jpeg
        - image/png
        - image/bmp
        - image/gif
    serverHost: http://rrow.xyz:83/

spring:
    servlet:
        multipart:
            max-file-size: 50MB         # \u8BBE\u7F6E\u6587\u4EF6\u4E0A\u4F20\u5927\u5C0F
            max-request-size: 50MB      # \u8BBE\u7F6E\u5355\u6B21\u8BF7\u6C42\u5927\u5C0F


