swagger3:
  base-package: com.study.controller
  name: test
  url: https://gitee.com/smiledouble
  version: 1.0
  group-name: test
  title: "测试"
  description: "测试swagger文档"
  license: gpt
  license-url: https://gitee.com/smiledouble
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss