server:
    port: 8080
spring:
    redis:
        host: localhost
        port: 6379
        database: 0
    rabbitmq:
        host: localhost
        port: 5672
        username: admin
        password: 123456
        virtual-host: /
        connection-timeout: 5000
