server:
    port: 8080
spring:
    application:
        name: mgb-application
    data:
        mongodb:
            host: 192.168.72.128
            port: 27017
            database: mgbstudy
            auto-index-creation: true
