spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rrow.xyz:3307/springboot?useUnicode=true&useSSL=false&characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: huangxiaodong
    type: com.alibaba.druid.pool.DruidDataSource      # 引入alibaba数据源
own:
  druid:
    monitor:
      list:
        - /druid/*
