spring:
  thymeleaf:
    cache: false    # \u5173\u95ED\u5F00\u542F\u7F13\u5B58\uFF0C\u9ED8\u8BA4\u662F\u5F00\u542F\u72B6\u6001

  mvc:
    format:
#      date: yyyy-MM-dd    # 可以手动配置接受过来字符串并根据接受的格式转换成Date类型
      date-time: yyyy-MM-dd HH:mm:ss