server:
    port: 8082
spring:
    application:
        name: loginservice
    redis:
        port: 6379
        database: 0
        host: localhost
eureka:
    client:
        service-url:
            defaultZone: http://rrow.xyz:8761/eureka
    instance:
        hostname: service3
        prefer-ip-address: true
        instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

